name: Setup environment and build on release
on:
  release:
    types: [created]
jobs:
  build:
    strategy:
      matrix:
        include:
        - platform: win
          arch: x64
        - platform: linux
          arch: x64
        - platform: linux
          arch: arm64
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12.0'
    - name: Clone external repository
      run: |
        git clone https://github.com/sp-tarkov/server
    - name: Checkout code
      run: |
        cd server
        git checkout 7a9a346bb2a08bffb965150784ca7869741804b1
        cd project/src/servers/
        rm HttpServer.ts
        wget https://raw.githubusercontent.com/wwng2333/spt_builder/main/HttpServer.ts
        cd ../..
    - name: Execute npm and build
      run: |
        cd server/project
        npm i
        npm run build:release -- --arch=${{ matrix.arch }} --platform=${{ matrix.platform }}
    - name: Uplaod files
      uses: actions/upload-artifact@v4
      with:
        name: SPT.Server_${{ matrix.platform }}-${{ matrix.arch }}
        path: server/project/build/SPT.Server.exe
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: server/project/build/SPT.Server.exe
        tag: ${{ github.ref }}
        asset_name: SPT.Server_${{ matrix.platform }}-${{ matrix.arch }}
