name: daily dev build
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *'
jobs:
  build:
    strategy:
      matrix:
        include:
        - platform: win
          arch: x64
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git git-lfs curl
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Clone external repository
      run: |
        git clone https://dev.sp-tarkov.com/SPT/Server.git
    - name: Checkout code
      run: |
        cd Server
        git checkout 3.10.0-DEV
        git-lfs pull
        cd project/src/servers/
        rm HttpServer.ts
        wget https://raw.githubusercontent.com/wwng2333/spt_builder/main/HttpServer.ts
        cd ../..
    - name: Execute npm and build
      run: |
        cd Server/project
        pnpm i
        npm run build:release -- --arch=${{ matrix.arch }} --platform=${{ matrix.platform }}
    - name: Uplaod files
      uses: actions/upload-artifact@v4
      with:
        name: SPT.Server_${{ matrix.platform }}-${{ matrix.arch }}
        path: Server/project/build/SPT.Server.exe
    - name: Packaging...
      run: tar czf SPT_Server-${{ matrix.arch }}-${{ matrix.platform }}.tgz Server/project/build/*
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Upload binaries to release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build ${{ steps.date.outputs.date }}"
        files: SPT_Server-${{ matrix.arch }}-${{ matrix.platform }}.tgz
